version: '1'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'my_postgres'
    environment:
      - 'POSTGRES_DB=postgre'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=mypassword'
    ports:
      - '5432:5432'