version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name : jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
    ports:
      - '8088:8080'

  postgres:
    image: 'postgres:latest'
    container_name: 'my_postgres'
    environment:
      - 'POSTGRES_DB=postgre'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=mypassword'

    ports:
      - '5432:5432'
  redis:
    image: 'redis:latest'
    container_name: 'my_redis'
    ports:
      - '6379:6379'
