server:
  port: 8084
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  spring:
    redis:
      host: 172.21.0.3
      port: 6379

  batch:
    job:
      enabled: true
      name: ${job.name:NONE}

  datasource:
#    url: jdbc:postgresql://172.21.0.2:5432/postgre?currentSchema=stock
    url: jdbc:postgresql://localhost:5432/postgre?currentSchema=stock
    username: myuser
    password: mypassword

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

logging:
  level:
    org.hibernate.SQL: debug

